### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by fabltd** [ncarlier/dockerfiles#4]
Docs states:

Build

For each subfolder: build image with make

How?  & where?

**Comment by ncarlier** [comment]
Example:
If you want to build yourself the MQTT image:
```bash
cd mqtt
make # to get available commands
make build # to build the image
```

**Comment by fabltd** [comment]
Thanks is this once inside the container?

**Comment by ncarlier** [comment]
No, all `make` commands have to be run on your docker host.
If you want to get in a container you can start a container with bash as entrypoint by using `make shell`. You will get a shell prompt inside the container.
Or if the container is running (with `make start`) you can use usual docker command: `docker exec -it <nameofyourcontainer>` to get in
